export const AVATARS = [
  { id: 1,  emoji: "🚴", bg: "#5760A6" },
  { id: 2,  emoji: "🏔️", bg: "#9462A6" },
  { id: 3,  emoji: "⚡", bg: "#007DB5" },
  { id: 4,  emoji: "🦁", bg: "#B8AED6" },
  { id: 5,  emoji: "🔥", bg: "#C0392B" },
  { id: 6,  emoji: "💨", bg: "#27AE60" },
  { id: 7,  emoji: "🎯", bg: "#F39C12" },
  { id: 8,  emoji: "🦅", bg: "#2C3E50" },
  { id: 9,  emoji: "⚙️", bg: "#7F8C8D" },
  { id: 10, emoji: "🌪️", bg: "#8E44AD" },
  { id: 11, emoji: "🏹", bg: "#D35400" },
  { id: 12, emoji: "🧗", bg: "#16A085" },
  { id: 13, emoji: "🐺", bg: "#2980B9" },
  { id: 14, emoji: "🎖️", bg: "#C0392B" },
  { id: 15, emoji: "🦊", bg: "#E67E22" },
];

export const NICKNAMES = [
  "De Waterdrager",
  "De Knecht",
  "De Wegkapitein",
  "De Vluchter",
  "De Sprinter",
  "De Klimmer",
  "De Tijdrijder",
  "De Baroudeur",
  "De Puncheur",
  "De Rouleur",
  "De Domestique",
  "De Kopman",
  "De Aanvaller",
  "De Verdediger",
  "De Klassementsrenner",
  "De Berggeit",
  "De Diesel",
  "De Raket",
  "De Torpedo",
  "De Kannibaal",
  "De Badger",
  "De Aigle",
  "De Buitenboordmotor",
  "De Haas",
  "De Schildpad",
  "De Locomotief",
  "De Metronoom",
  "De Kanonskogel",
  "De Schaduw",
  "De Onruststoker",
  "De Eenzame Wolf",
  "De Alleskunner",
  "De Pijlsnelle",
  "De Stoïcijn",
  "De Vliegende Hollander",
  "De Stille Kracht",
  "De Bergkoning",
  "De Puncher",
  "De Finisher",
  "De Takticus",
];

export function getAvatar(id: number | null | undefined) {
  return AVATARS.find((a) => a.id === id) ?? AVATARS[0];
}
